# Generated by Django 3.2 on 2021-05-02 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionHotel', '0002_auto_20210502_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='email_client',
            new_name='email_employee',
        ),
    ]
